apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: faultmanagementconfigurations.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: FaultManagementConfiguration
    listKind: FaultManagementConfigurationList
    plural: faultmanagementconfigurations
    singular: faultmanagementconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FaultManagementConfiguration is the Schema for the faultmanagementconfigurations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FaultManagementConfigurationSpec  configures fault management
            type: object
          status:
            description: FaultManagementConfigurationStatus defines the observed state
              of FaultManagementConfiguration
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
